name       : libayatana-ido
version    : 0.8.2
release    : 1
source     :
    - https://github.com/AyatanaIndicators/ayatana-ido/archive/refs/tags/0.8.2.tar.gz : 4d5cb5df9ab5b8e5fbe47caf077aa001d167bad5ee80df825b910d83904ac777
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Custom GTK menu widgets for Ayatana System Indicators
description: |
    Custom GTK menu widgets for Ayatana System Indicators.
emul32     : yes
builddeps  :
    - pkgconfig32(gtk+-3.0)
    - gtk-doc
    - mate-common
    - vala
setup      : |
    # NOCONFIGURE avoids to configure twice: one in autogen.sh, another in ./configure.
    NOCONFIGURE=1 %autogen
build      : |
    %make
install    : |
    %make_install
