name       : libayatana-ido
version    : 0.10.0
release    : 3
source     :
    - https://github.com/AyatanaIndicators/ayatana-ido/archive/refs/tags/0.10.0.tar.gz : d6ec310572de38c6b5c4ca9ff0979366a3c783af14bb47113cab5da7d5946fa7
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Custom GTK menu widgets for Ayatana System Indicators
description: |
    Custom GTK menu widgets for Ayatana System Indicators.
emul32     : yes
builddeps  :
    - pkgconfig32(gtk+-3.0)
    - gtk-doc
    - mate-common
    - vala
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
